package bodiGenerator.dataSource;

import java.util.List;


/**
 * The object generated by a {@link Statement} query in a {@link TabularDataSource}
 * <p>
 * Representation of a tabular data structure, that is, data organized as a table. Its structure and behaviour is
 * similar to {@link TabularDataSource}. The difference is that {@link ResultSet} is generated from a
 * {@link TabularDataSource},
 * and a {@link TabularDataSource} is generated from a tabular file such as csv.
 * @see TabularDataSource
 * @see Statement
 * @see Statement#executeQuery()
 */
public class ResultSet {

    /**
     * The number of rows of the {@link ResultSet}. It is always equal to {@link #table} size
     */
    private int numRows;

    /**
     * The number of columns of the {@link ResultSet}. It is always equal to {@link #header} size and the
     * size of each {@link Row} in {@link #table}.
     */
    private int numColumns;

    /**
     * The header of the {@link ResultSet}. It contains the name of its columns.
     */
    private List<String> header;

    /**
     * The content of the {@link ResultSet}. It is organized by rows, each one represented as a {@link Row} object.
     * <p>
     * The size of each row is equal to the size of the {@link #header} (empty cells are not skipped)
     */
    private List<Row> table;

    /**
     * Instantiates a new {@link ResultSet}.
     *
     * @param header the header
     * @param table  the table
     */
    public ResultSet(List<String> header, List<Row> table) {
        this.header = header;
        this.table = table;
        numColumns = header.size();
        numRows = table.size();
    }

    /**
     * Gets a row from {@link #table}.
     *
     * @param i the index of the row in {@link #table}
     * @return the row at index {@code i} in {@link #table}
     */
    public Row getRow(int i) {
        return table.get(i);
    }

    /**
     * Gets the number of rows of the {@link ResultSet}.
     *
     * @return the number of rows
     */
    public int getNumRows() {
        return numRows;
    }

    /**
     * Gets the number of columns of the {@link ResultSet}.
     *
     * @return the number of columns
     */
    public int getNumColumns() {
        return numColumns;
    }

    /**
     * Gets the {@link #header} of the {@link ResultSet}
     *
     * @return the header
     */
    public List<String> getHeader() {
        return header;
    }

}
